### ISSUE TITLE
Final proofread

### ISSUE THREAD

**Issue by lifenautjoe** [OpenbookOrg/openbook-org-www#38]
Access to the staging version of the site has been given to several people for proofreading.

This issue is to commit those changes back.

**Comment by lifenautjoe** [comment]
On manifesto o claim back our privacy => to claim back our privacy

**Comment by lifenautjoe** [comment]
On jobs, We are embarking in one of the most exciting => We are embarking **on** one of the most exciting

**Comment by evict** [comment]
home > All of our code free and open for everyone to inspect, reproduce and contribute to.
Proposed: All of our code **is** free and open for everyone to inspect, reproduce and contribute to.

manifesto > The box below appears in your screen. 
Proposed: The box below appears **on** your screen.

jobs > If you believe in Openbook and are talented in what you do...
Proposed: If you believe in Openbook and are talented **that** what you do...

faq > However, if your concern is data portability, all of your data will downloadable and fully portable to other Openbook instances.
Proposed: However, if your concern is data portability, all of your data will **be** downloadable and fully portable to other Openbook instances.

faq > There's many ways you can help right now.
Proposed: There **are** many ways you can help right now.

faq > Here's some ideas
Proposed: Here **are** some ideas:
