### ISSUE TITLE
FB link is broken

### ISSUE THREAD

**Issue by lifenautjoe** [OpenbookOrg/openbook-org-www#68]
We changed the FB username for the Openbook page. The links on the website are broken. Update to https://www.facebook.com/openbooksocial/

**Comment by thadguidry** [comment]
I need a new home (bye bye G+ in 2019) ... thanks for opening the door, Openbook. I'm in.

**Comment by lifenautjoe** [comment]
Hi Thad! Thanks for the PR ! And looking forward to seeing you @ Openbook !
🎉
