### ISSUE TITLE
Adding bigger versions of customization examples

### ISSUE THREAD

**Issue by colomar** [OpenbookOrg/openbook-org-www#73]
Whenever I see small thumbnails of interesting screenshots or mockups, as a user I immediately want to click on them to see larger versions of them, such as the mockups at the top of the "home" page as well as the ones in the "customisable" section.
I'd be willing to add a feature to show the images in a lightbox on click, but I can't find larger versions of the images in the source code.
Of course this might be because you think it's too early to show bigger images of the current state to the world yet, though if that's the case I'd suggest reconsidering, because I believe that even if the images just show mockups they'd still be interesting to people in bigger versions).
So, if possible it would be great if you could add higher-res versions of the images in /src/views/home/components/personal/components/customization-screenshots/assets/ and src/views/home/components/splash-hero/assets/ to the repo so I could try to show them on click on a thumbnail.
If you dislike the idea of showing bigger mockups, that's okay of course.

**Comment by lifenautjoe** [comment]
Section of desktop mockups is gone so closing issue 😬
