### ISSUE TITLE
Consider ActivityPub

### ISSUE THREAD

**Issue by jeroenpraat** [OpenbookOrg/openbook-org-www#84]
In the FAQ I read: 

"Will Openbook be decentralised?

We want to get there eventually. We’re looking into Solid MIT approach (The one from Tim Berners Lee) and we’re very pleased with it so far."

Please consider implementing [ActivityPub](https://www.w3.org/TR/activitypub/)! It's a W3C standard and is already live on multiple projects (incl. Mastodon). It can even work when Openbook is still centralized. 

See also [Wikipedia](https://en.wikipedia.org/wiki/ActivityPub). Don't make Openbook the next walled garden!

**Comment by DeadSuperHero** [comment]
Would definitely be interesting to see OpenBook join the fediverse - currently about half a dozen or so open platforms support the protocol, and a lot of work is going into ensuring that they can all successfully inter-federate with one another.

**Comment by jeroenpraat** [comment]
Moved to https://github.com/OpenbookOrg/openbook-app/issues/115 (still unclear to me if it fits there, but there's much more development over there). cc @DeadSuperHero
